package com.example.romai.myapplication;
// nous avons eu des probleme avec
public class BDD {
    [
    {
        "id":2,
            "nom":"Doof Wagon",
            "image":"zoom-doof-wagon.jpg",
            "disponible":1,
            "prixjournalierbase":79,
            "promotion":10,
            "agemin":25,
            "categorieco2":"G",
            "equipements":[
        {
            "id":1,
                "nom":"Climatisation"
        },
        {
            "id":5,
                "nom":"Auto-radio"
        }
      ],
        "options":[
        {
            "id":2,
                "nom":"Lance-flamme",
                "prix":49
        },
        {
            "id":1,
                "nom":"Mitrailleuse",
                "prix":29
        }
      ]
    },
    {
        "id":4,
            "nom":"Interceptor",
            "image":"zoom-interceptor.jpg",
            "disponible":1,
            "prixjournalierbase":39,
            "promotion":0,
            "agemin":18,
            "categorieco2":"G",
            "equipements":[
        {
            "id":2,
                "nom":"Direction assist\u00e9e"
        }
      ],
        "options":[
        {
            "id":1,
                "nom":"Mitrailleuse",
                "prix":29
        }
      ]
    },
    {
        "id":5,
            "nom":"Mack",
            "image":"zoom-mack.jpg",
            "disponible":1,
            "prixjournalierbase":39,
            "promotion":0,
            "agemin":21,
            "categorieco2":"G",
            "equipements":[
        {
            "id":2,
                "nom":"Direction assist\u00e9e"
        },
        {
            "id":5,
                "nom":"Auto-radio"
        }
      ],
        "options":[
        {
            "id":1,
                "nom":"Mitrailleuse",
                "prix":29
        },
        {
            "id":2,
                "nom":"Lance-flamme",
                "prix":49
        }
      ]
    },
    {
        "id":6,
            "nom":"Mad Grandma",
            "image":"zoom-mad-grandma.jpg",
            "disponible":1,
            "prixjournalierbase":29,
            "promotion":30,
            "agemin":18,
            "categorieco2":"G",
            "equipements":[
        {
            "id":1,
                "nom":"Climatisation"
        },
        {
            "id":2,
                "nom":"Direction assist\u00e9e"
        },
        {
            "id":3,
                "nom":"To\u00eet ouvrant"
        },
        {
            "id":4,
                "nom":"Si\u00e8ge chauffant"
        }
      ],
        "options":[

      ]
    },
    {
        "id":7,
            "nom":"Mad Pickup",
            "image":"zoom-mad-pickup.jpg",
            "disponible":1,
            "prixjournalierbase":39,
            "promotion":0,
            "agemin":23,
            "categorieco2":"G",
            "equipements":[
        {
            "id":1,
                "nom":"Climatisation"
        },
        {
            "id":2,
                "nom":"Direction assist\u00e9e"
        },
        {
            "id":5,
                "nom":"Auto-radio"
        }
      ],
        "options":[
        {
            "id":1,
                "nom":"Mitrailleuse",
                "prix":29
        },
        {
            "id":3,
                "nom":"Scie-circulaire",
                "prix":59
        }
      ]
    },
    {
        "id":8,
            "nom":"Peace Maker",
            "image":"zoom-peacemaker.jpg",
            "disponible":1,
            "prixjournalierbase":35,
            "promotion":25,
            "agemin":18,
            "categorieco2":"G",
            "equipements":[
        {
            "id":2,
                "nom":"Direction assist\u00e9e"
        },
        {
            "id":3,
                "nom":"To\u00eet ouvrant"
        }
      ],
        "options":[
        {
            "id":3,
                "nom":"Scie-circulaire",
                "prix":59
        },
        {
            "id":2,
                "nom":"Lance-flamme",
                "prix":49
        }
      ]
    },
    {
        "id":9,
            "nom":"People Eater",
            "image":"zoom-people-eater.jpg",
            "disponible":1,
            "prixjournalierbase":89,
            "promotion":10,
            "agemin":25,
            "categorieco2":"G",
            "equipements":[
        {
            "id":1,
                "nom":"Climatisation"
        },
        {
            "id":2,
                "nom":"Direction assist\u00e9e"
        },
        {
            "id":3,
                "nom":"To\u00eet ouvrant"
        },
        {
            "id":4,
                "nom":"Si\u00e8ge chauffant"
        }
      ],
        "options":[
        {
            "id":1,
                "nom":"Mitrailleuse",
                "prix":29
        },
        {
            "id":3,
                "nom":"Scie-circulaire",
                "prix":59
        },
        {
            "id":2,
                "nom":"Lance-flamme",
                "prix":49
        }
      ]
    },
    {
        "id":10,
            "nom":"Plymouth Rock",
            "image":"zoom-plymouth-rock.jpg",
            "disponible":1,
            "prixjournalierbase":25,
            "promotion":0,
            "agemin":18,
            "categorieco2":"G",
            "equipements":[
        {
            "id":2,
                "nom":"Direction assist\u00e9e"
        },
        {
            "id":3,
                "nom":"To\u00eet ouvrant"
        },
        {
            "id":4,
                "nom":"Si\u00e8ge chauffant"
        }
      ],
        "options":[
        {
            "id":3,
                "nom":"Scie-circulaire",
                "prix":59
        },
        {
            "id":1,
                "nom":"Mitrailleuse",
                "prix":29
        }
      ]
    },
    {
        "id":11,
            "nom":"The Bigfoot",
            "image":"zoom-the-big-foot.jpg",
            "disponible":1,
            "prixjournalierbase":49,
            "promotion":0,
            "agemin":23,
            "categorieco2":"G",
            "equipements":[
        {
            "id":1,
                "nom":"Climatisation"
        },
        {
            "id":2,
                "nom":"Direction assist\u00e9e"
        }
      ],
        "options":[
        {
            "id":2,
                "nom":"Lance-flamme",
                "prix":49
        }
      ]
    },
    {
        "id":12,
            "nom":"The Giga Horse",
            "image":"zoom-the-gigahorse.jpg",
            "disponible":1,
            "prixjournalierbase":65,
            "promotion":0,
            "agemin":23,
            "categorieco2":"G",
            "equipements":[

      ],
        "options":[

      ]
    },
    {
        "id":13,
            "nom":"The Nux Car",
            "image":"zoom-the-nux-car.jpg",
            "disponible":1,
            "prixjournalierbase":29,
            "promotion":15,
            "agemin":18,
            "categorieco2":"G",
            "equipements":[
        {
            "id":2,
                "nom":"Direction assist\u00e9e"
        },
        {
            "id":3,
                "nom":"To\u00eet ouvrant"
        },
        {
            "id":5,
                "nom":"Auto-radio"
        }
      ],
        "options":[
        {
            "id":1,
                "nom":"Mitrailleuse",
                "prix":29
        },
        {
            "id":2,
                "nom":"Lance-flamme",
                "prix":49
        }
      ]
    },
    {
        "id":14,
            "nom":"The War Rig",
            "image":"zoom-the-war-rig.jpg",
            "disponible":1,
            "prixjournalierbase":89,
            "promotion":0,
            "agemin":25,
            "categorieco2":"G",
            "equipements":[
        {
            "id":1,
                "nom":"Climatisation"
        },
        {
            "id":2,
                "nom":"Direction assist\u00e9e"
        }
      ],
        "options":[
        {
            "id":1,
                "nom":"Mitrailleuse",
                "prix":29
        },
        {
            "id":2,
                "nom":"Lance-flamme",
                "prix":49
        }
      ]
    },
    {
        "id":15,
            "nom":"You Shall Not Pass",
            "image":"zoom-you-shall-not-pass.jpg",
            "disponible":1,
            "prixjournalierbase":35,
            "promotion":0,
            "agemin":21,
            "categorieco2":"G",
            "equipements":[
        {
            "id":2,
                "nom":"Direction assist\u00e9e"
        }
      ],
        "options":[
        {
            "id":3,
                "nom":"Scie-circulaire",
                "prix":59
        },
        {
            "id":1,
                "nom":"Mitrailleuse",
                "prix":29
        }
      ]
    }
]
}
